export enum EAppStages {
  APP_START = 'APP_STAGES@APP_START',
  ONLINE_GAME_SEARCH = 'APP_STAGES@ONLINE_GAME_SEARCH',
  GAME_IN_PROGRESS = 'APP_STAGES@GAME_IN_PROGRESS',
  GAME_OVER = 'APP_STAGES@GAME_OVER',
}
