export enum ESocketEvents {
  PLAYER_MOVE = 'SOCKET_EVENTS@PLAYER_MOVE',
  SEND_MOVE = 'SOCKET_EVENTS@SEND_MOVE',
  RECEIVE_MOVE = 'SOCKET_EVENTS@RECEIVE_MOVE',
  OPPONENT_FOUND = 'SOCKET_EVENTS@OPPONENT_FOUND',
}
