export enum EAppActionTypes {
  // game modes
  SET_APP_STAGE = 'APP@SET_APP_STAGE',
  // main menu
  HIDE_MENU = 'APP@HIDE_MENU',
  SHOW_MENU = 'APP@SHOW_MENU',
  TOGGLE_MENU = 'APP@TOGGLE_MENU',
  // spinner
  SHOW_SPINNER = 'APP@SHOW_SPINNER',
  HIDE_SPINNER = 'APP@HIDE_SPINNER',
  TOGGLE_SPINNER = 'APP@TOGGLE_SPINNER',
}
