export enum EGameActionTypes {
  // init
  INIT_SINGLE_GAME = 'GAME@INIT_SINGLE_GAME',
  INIT_ONLINE_GAME = 'GAME@INIT_ONLINE_GAME',
  INIT_OWN_FIELD = 'GAME@INIT_OWN_FIELD',
  SET_OWN_FIELD = 'GAME@SET_OWN_FIELD',
  // UI elements visibility
  SHOW_OPPONENT_FIELD = 'GAME@SHOW_OPPONENT_FIELD',
  HIDE_OPPONENT_FIELD = 'GAME@HIDE_OPPONENT_FIELD',
  // flow
  SEND_SPELL = 'GAME@SEND_SPELL',
  LEAVE_ONLINE_GAME = 'GAME@LEAVE_ONLINE_GAME',
  SET_GAME_STATUS = 'GAME@SET_GAME_STATUS',
  // spells
  DESTROY_OWN_CELL = 'GAME@DESTROY_OWN_CELL',
}
