export enum ETerminalActionTypes {
  // terminal visibility
  SHOW_TERMINAL = 'TERMINAL@SHOW_TERMINAL',
  HIDE_TERMINAL = 'TERMINAL@HIDE_TERMINAL',
  TOGGLE_TERMINAL = 'TERMINAL@TOGGLE_TERMINAL',
  // spelling
  CAST_SPELL = 'TERMINAL@CAST_SPELL',
  ADD_TO_HISTORY = 'TERMINAL@ADD_TO_HISTORY',
}
