export enum ETerminalActionTypes {
  // terminal visibility
  SHOW_TERMINAL = 'TERMINAL@SHOW_TERMINAL',
  HIDE_TERMINAL = 'TERMINAL@HIDE_TERMINAL',
  TOGGLE_TERMINAL = 'TERMINAL@TOGGLE_TERMINAL',
  FOCUS_TERMINAL = 'TERMINAL@FOCUS_TERMINAL',
  UNFOCUS_TERMINAL = 'TERMINAL@UNFOCUS_TERMINAL',
  TOGGLE_TERMINAL_FOCUS = 'TERMINAL@TOGGLE_TERMINAL_FOCUS',
  // spelling
  CAST_SPELL = 'TERMINAL@CAST_SPELL',
  ADD_TO_HISTORY = 'TERMINAL@ADD_TO_HISTORY',
}
